// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTransferSystem.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MoneyTransferSystem.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201215000957_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MoneyTransferSystem.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("Money")
                        .HasColumnType("double precision");

                    b.Property<string>("UserLogin")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserLogin");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MoneyTransferSystem.Models.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Pass")
                        .HasColumnType("text");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoneyTransferSystem.Models.Account", b =>
                {
                    b.HasOne("MoneyTransferSystem.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserLogin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyTransferSystem.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
